PCB: false
batchsize: 32
color_jitter: false
data_dir: ../Market/pytorch
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
lr: 0.05
name: ft_ResNet50
stride: 2
train_all: true
use_dense: false
use_NAS: false
use_swin: false
use_swinv2: false
use_convnext: false
use_efficient: false
use_hr: false
nclasses: 751
